# Generated by Django 5.2.6 on 2025-10-03 00:36

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    """
    Creates a superuser using environment variables for credentials.
    """
    CustomUser = apps.get_model('accounts', 'CustomUser')
    
    ADMIN_USERNAME = os.environ.get('ADMIN_USERNAME')
    ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')
    ADMIN_PASSWORD = os.environ.get('ADMIN_PASSWORD')

    if ADMIN_USERNAME and ADMIN_EMAIL and ADMIN_PASSWORD:
        if not CustomUser.objects.filter(username=ADMIN_USERNAME).exists():
            print(f"Creating superuser: {ADMIN_USERNAME}")
            CustomUser.objects.create_superuser(
                username=ADMIN_USERNAME,
                email=ADMIN_EMAIL,
                password=ADMIN_PASSWORD
            )
        else:
            print(f"Superuser {ADMIN_USERNAME} already exists.")
    else:
        print("Superuser environment variables not set. Skipping creation.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
